solidago canadensis
schizachyrium scoparium
pycnanthemum virginianum
asclepias syriaca
diervilla lonicera
abies balsamea
rhododendron prinophyllum
euonymus atropurpureus
antennaria plantaginifolia
rudbeckia hirta
schoenoplectus pungens
veronicastrum virginicum
peltandra virginica
cyperus esculentus
lilium canadense
sparganium eurycarpum
amphicarpaea bracteata
amelanchier arborea
arisaema dracontium
andromeda polifolia
rhododendron groenlandicum
spiraea latifolia
physocarpus opulifolius
helianthus giganteus
fraxinus pennsylvanica
asclepias tuberosa
persicaria sagittata
phlox subulata
juniperus communis
ilex verticillata
liriodendron tulipifera
vaccinium stamineum
typha latifolia
salix humilis var humilis
lepidium virginicum
streptopus lanceolatus
physalis heterophylla
saururus cernuus
symplocarpus foetidus
aronia melanocarpa
rubus flagellaris
chamaenerion angustifolium
solidago altissima
acer saccharum
apocynum androsaemifolium
pinus resinosa
gentiana andrewsii
ageratina altissima
viola pedata
brasenia schreberi
mentha arvensis
geranium maculatum
gentiana saponaria
leersia oryzoides
hieracium umbellatum
liatris cylindracea
descurainia pinnata
rhododendron periclymenoides
epigaea repens
acer nigrum
juniperus virginiana
kalmia latifolia
cornus obliqua
picea glauca
euphorbia corollata
lobelia cardinalis
crataegus punctata
oenothera perennis
lathyrus ochroleucus
erigeron annuus
vallisneria americana
ceratophyllum demersum
boehmeria cylindrica
apios americana
euthamia graminifolia
magnolia acuminata
eutrochium purpureum
salix discolor
verbena hastata
vitis riparia
phlox divaricata
claytonia caroliniana
chelone glabra
solidago nemoralis
lathyrus japonicus
symphyotrichum lateriflorum
symphyotrichum cordifolium
betula lenta
corylus americana
lonicera oblongifolia
fraxinus nigra
sassafras albidum
equisetum scirpoides
glyceria striata
rosa carolina
arctostaphylos uva ursi
asimina triloba
parthenocissus inserta
pycnanthemum tenuifolium
oenothera biennis
symphyotrichum patens
claytonia virginica
fragaria virginiana
quercus macrocarpa
solidago caesia
ambrosia artemisiifolia
quercus montana
vaccinium macrocarpon
cryptotaenia canadensis
coptis trifolia
solidago ohioensis
impatiens capensis
cornus florida
sagittaria graminea
solidago odora
rhus glabra
carya laciniosa
prunus virginiana
sparganium americanum
adlumia fungosa
quercus rubra
symphyotrichum puniceum
cicuta maculata
solidago gigantea
sporobolus neglectus
schoenoplectus fluviatilis
prunus serotina
ribes triste
aronia prunifolia
phytolacca americana
solidago rigida
rudbeckia laciniata
ammophila breviligulata
physalis longifolia
rosa virginiana
ranunculus sceleratus
rhus typhina
quercus bicolor
juncus bufonius
spartina pectinata
larix laricina
parthenocissus quinquefolia
viola labradorica
persicaria amphibia
erigeron philadelphicus
cornus amomum
aralia racemosa
rubus hispidus
cirsium discolor
physostegia virginiana
taxus canadensis
hamamelis virginiana
maianthemum racemosum
solidago hispida
solidago uliginosa
cuscuta gronovii
decodon verticillatus
sporobolus vaginiflorus
zizia aurea
lupinus perennis
vaccinium pallidum
maianthemum stellatum
ulmus rubra
helianthus divaricatus
nyssa sylvatica
acer spicatum
veronica peregrina
salix bebbiana
symphoricarpos albus
lemna minor
asclepias incarnata
verbena urticifolia
cornus drummondii
acer saccharinum
agastache nepetoides
amelanchier laevis
staphylea trifolia
erigeron pulchellus
platanus occidentalis
schoenoplectus tabernaemontani
acer pensylvanicum
lilium philadelphicum
actaea racemosa
leersia virginica
oxalis stricta
persicaria lapathifolia
antennaria neglecta
panicum dichotomiflorum
zannichellia palustris
acer negundo
equisetum fluviatile
corylus cornuta
equisetum arvense
bidens tripartita
smilax herbacea
ulmus thomasii
persicaria virginiana
quercus alba
comptonia peregrina
quercus muehlenbergii
eurybia macrophylla
betula alleghaniensis
ceanothus americanus
galium boreale
rosa palustris
echinochloa muricata
pinus strobus
cornus alba
prunus americana
elodea canadensis
juglans cinerea
salix interior
calla palustris
oenothera fruticosa
anaphalis margaritacea
polystichum acrostichoides
spiraea alba
aralia spinosa
thuja occidentalis
celtis occidentalis
equisetum hyemale
symphyotrichum novi belgii
apocynum cannabinum
tsuga canadensis
salix petiolaris
lonicera canadensis
chamaedaphne calyculata
symphyotrichum ericoides
pycnanthemum incanum
carpinus caroliniana
viola blanda
persicaria hydropiperoides
juglans nigra
smilax hispida
podophyllum peltatum
rosa setigera
achillea millefolium
lobelia siphilitica
equisetum variegatum
salix humilis
viburnum acerifolium
vaccinium oxycoccos
packera aurea
rudbeckia triloba
carya cordiformis
solidago ulmifolia
mitchella repens
euonymus obovatus
actaea rubra
matricaria discoidea
lithospermum canescens
shepherdia canadensis
celastrus scandens
ptelea trifoliata
viburnum lentago
monarda fistulosa
sambucus racemosa
betula populifolia
ribes glandulosum
acer rubrum
solidago rugosa
rubus allegheniensis
solanum carolinense
persicaria pensylvanica
arisaema triphyllum
comandra umbellata
viola pubescens
symphyotrichum novae angliae
carya tomentosa
cephalanthus occidentalis
eutrochium maculatum
crataegus crus galli
rhus aromatica
ulmus americana
asclepias variegata
oenothera gaura
populus tremuloides
symphyotrichum laeve
clinopodium arkansanum
aquilegia canadensis
zanthoxylum americanum
rhododendron maximum
viola striata
viola sororia
vaccinium corymbosum
heliopsis helianthoides
amelanchier sanguinea
glyceria grandis
carya glabra
solidago juncea
fagus grandifolia
euonymus americanus
impatiens pallida
cornus racemosa
ranunculus abortivus
menispermum canadense
ilex montana
caulophyllum thalictroides
helenium autumnale
asclepias verticillata
viburnum rafinesquianum
sagittaria latifolia
gaylussacia baccata
castanea dentata
hibiscus moscheutos
chamaecrista fasciculata
lindera benzoin
dirca palustris
pontederia cordata
solidago flexicaulis
campanula rotundifolia
potamogeton illinoensis
eupatorium perfoliatum
rubus occidentalis
gaultheria procumbens
aralia nudicaulis
salix eriocephala
castilleja coccinea
morus rubra
deschampsia caespitosa
gaultheria hispidula
hieracium scabrum
tilia americana
ostrya virginiana
proserpinaca palustris
scirpus pendulus
fraxinus americana
cakile edentula
viburnum recognitum
smilax rotundifolia
quercus palustris
